### ISSUE TITLE
Rancher support for Imported Windows EKS cluster

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#296] opened 2023-11-24 11:14 UTC
Spike to evaluate the possibility (and effort) to add windows nodes support for imported EKS cluster.

**Comment by mjura** [comment] 2023-12-05 11:38
I have re-tested once again `Windows` worker nodes support for EKS hosted provider. After cluster provisioning it was needed to enable Windows Support for EKS cluster based on Amazon documentation:
https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#enable-windows-support

After it, I used test Windows application deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-server-iis-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: windows-server-iis-test
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: windows-server-iis-test
        tier: backend
        track: stable
    spec:
      containers:
      - name: windows-server-iis-test
        image: mcr.microsoft.com/windows/servercore:1809
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
        command:
        - powershell.exe
        - -command
        - "Add-WindowsFeature Web-Server; Invoke-WebRequest -UseBasicParsing -Uri 'https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.6/ServiceMonitor.exe' -OutFile 'C:\\ServiceMonitor.exe'; echo '<html><body><br/><br/><marquee><H1>Hello EKS!!!<H1><marquee></body><html>' > C:\\inetpub\\wwwroot\\default.html; C:\\ServiceMonitor.exe 'w3svc'; "
        resources:
          limits:
            cpu: 256m
            memory: 256Mi
          requests:
            cpu: 128m
            memory: 100Mi
      nodeSelector:
        kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: windows-server-iis-test
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: windows-server-iis-test
    tier: backend
    track: stable
  sessionAffinity: None
  type: ClusterIP
```

**Comment by mjura** [comment] 2023-12-05 11:39
As the result of this operations, example application was deployed and it was possible to view Workload from Rancher UI.

![eks-windows-deployment](https://github.com/rancher/eks-operator/assets/4455471/4a3a0f5f-828f-4dfd-8076-8f2ccbee04ed)

![eks-windows-pods](https://github.com/rancher/eks-operator/assets/4455471/b7f6ab60-3cdf-42a5-906f-1fc365823e27)

**Comment by mjura** [comment] 2023-12-05 11:41
Currently minor bug might be that Windows CPU and memory metrics are not present 

![eks-nodes-metrics](https://github.com/rancher/eks-operator/assets/4455471/7f2029d4-4c9f-4d9e-ae07-1c1a459691ba)

This problem seems to work fine after `metrics-server` installation

```console
mjura@gecko:~/> kubectl top nodes
NAME                              CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ip-192-168-137-49.ec2.internal    69m          3%     983Mi           29%       
ip-192-168-176-128.ec2.internal   1m           0%     351Mi           4%        
ip-192-168-200-83.ec2.internal    1m           0%     534Mi           6%        
ip-192-168-246-173.ec2.internal   61m          3%     645Mi           19%       
mjura@gecko:~/> kubectl top pods -n test
NAME                                  CPU(cores)   MEMORY(bytes)   
windows-server-iis-5cbc5bc99c-mc96g   0m           116Mi        
```

**Comment by kkaempf** [comment] 2023-12-05 13:04
So it's a documentation issue ?

**Comment by mjura** [comment] 2023-12-07 10:54
> So it's a documentation issue ?

The problem is with showing CPU and memory metrics in Rancher UI, probably because rancher-agent can't get it. It is investigation for Rancher Core

**Comment by mjura** [comment] 2023-12-13 10:30
Adding CPU and memory metrics will be added in https://github.com/rancher/windows/issues/223. Currently we are waiting for customer feedback if workaround with metrics-server is enough

**Comment by sadhugit** [comment] 2024-02-07 06:29
A workaround with the metric server needs to be revised as the customer checks for metrics details in the Rancher UI. where metrics show NA and kubectl top commands offer the output.  No agent/ node exporter runs on nodes to export the metrics details.

**Comment by mjura** [comment] 2024-02-08 10:47
we are awaiting for this feature to be tested/implemented: https://github.com/rancher/windows/issues/223

As workaround until then please install metric-server

```
 install `metrics-server`

 

```console

helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/

helm repo update

helm install --create-namespace -n metrics-server metrics-server metrics-server/metrics-server
```

**Comment by mjura** [comment] 2024-02-08 10:48
@kkaempf Highlander Team is done with this issue, can we close it ?

**Comment by kkaempf** [comment] 2024-02-08 14:23
Yes

**Closed** 2024-06-25 09:12 UTC
Labels: status/duplicate, kind/spike, platform/windows
