### ISSUE TITLE
[SURE-3752]  [EKS] Allow the managed node group warning to be cleared

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#301] opened 2023-12-06 13:50 UTC
### Business case

Using self-managed node groups from a registered EKS cluster is at times preferred or desired, the warning adds an annoyance to the Rancher experience. 

### Request description:

Allow the warning for 'Cluster must have at least one managed nodegroup' to be cleared, or informational

### Actual behavior:
Red warning is always present in the UI

### Expected behavior:
When the cluster is functioning as usual, cluster-agent is deployed and there are nodes registered, the warning is unnecessary.

This could also be confirmed via the EKS API endpoint or detecting a cluster-agent tunnel connection, if it was able to be cleared this would provide a way for users to remove the warning.

### Workaround:
Is workaround available and implemented? no (kind of)
What is the workaround: Add a managed node group

### PR's
- [x] https://github.com/rancher/rancher/pull/43882
- [x] https://github.com/rancher/rancher/pull/43881
- [ ] https://github.com/rancher/rancher-docs/pull/1048

**Comment by kkaempf** [comment] 2023-12-06 13:52
see also https://github.com/rancher/dashboard/issues/9618

**Comment by salasberryfin** [comment] 2023-12-18 10:02
@mjura and I investigated this issue and found some relevant details:

- We have validated that, if the EKS cluster uses self-managed node groups, Rancher is able to deploy the agent to the existing instances and appear as `Active` in the dashboard. When the number of instances in the self-managed node group is set to 0, or instances are not properly associated with the cluster, the agent won't be deployed and the cluster will be `Waiting`. The screenshot in the original issue, shows that `moon-imported` has 0 machines available, which is most likely the root cause of the issue.
- Even though the agent can be deployed when there are no managed node groups, the cluster specification is designed to use this type of compute for EKS clusters, so behavior may be unstable in specific situations.

Furthermore, **the design docs state that only using managed node groups is supported** in EKS. You can read about this decision [here](https://confluence.suse.com/display/RMI/Kontainer+Engine+2.0+-+Design+Doc).

We consider this enough to close this issue.

**Comment by mjura** [comment] 2023-12-27 11:43
This will be fixed in https://github.com/rancher/rancher/pull/43881

**Comment by mjura** [comment] 2023-12-28 13:05
Documentation part https://github.com/rancher/rancher-docs/pull/1048

**Comment by cpinjani** [comment] 2024-01-26 10:05
Verified as fixed on builds:
```
v2.8-d0a177f1745fe14a0b3de7483aa3ef895d1ab967-head
v2.9-b57600cdc9b427f30f6c964ad46c535cce8f5c86-head
```

Able to import EKS cluster with self-managed nodes - :white_check_mark: 
Error "_Cluster must have at least one managed nodegroup_" is not displayed and cluster can be explored - :white_check_mark: 

![image](https://github.com/rancher/eks-operator/assets/73099870/76838b59-e351-41ed-b3f8-5e2eaa133dcc)

**Closed by cpinjani** 2024-01-26 10:05 UTC
Labels: kind/bug, JIRA, kind/usability
