### ISSUE TITLE
EKS: Unexpected error in logs while recording failure message

### ISSUE THREAD

**Issue by cpinjani** [rancher/eks-operator#596] opened 2024-06-11 08:12 UTC
**Rancher version:**
Rancher version: v2.9-3142335ab9b375b6e2c26270f80a4bcb727bd652-head
eks-operator: v1.9.0-rc.5

Cluster Type: Downstream EKS cluster

**Describe the bug:**
Unexpected error in logs while recording failure message
See also: https://github.com/rancher/eks-operator/issues/541

**Logs:**
- time="2024-06-09T14:29:53Z" level=error msg="**Error recording ekscc [] failure message**: resource name may not be empty"

- time="2024-06-09T15:34:17Z" level=error msg="**Error recording ekscc [] failure message**: Operation cannot be fulfilled on eksclusterconfigs.eks.cattle.io "c-hhwnb": the object has been modified; please apply your changes to the latest version and try again"

**Comment by thehejik** [comment] 2024-10-03 14:58
### Test report
The problem seems to be fixed in latest available version of EKS operator `rancher-eks-operator:104.3.0+up1.9.3-rc.1` on rancher `v2.9-9877ad6f8a6805de6314d739b7023a4a075f525a-head`.

#### Reproducer
• provision EKS from rancher with default values
• via Edit Config in Rancher add a NG to the EKS cluster with 1 node with Volume size = 1GB  (minimal allowed is 20GB)
• open and watch eks operator logs
• wait for Status Error 400: `InvalidRequestException: Volume of size 1GB is smaller than snapshot`
• Edit the cluster again and remove the problematic new NG and watch logs, something like this will appear:
```
time="2024-10-03T10:09:57Z" level=error msg="error syncing 'cattle-global-data/c-jkqpn': handler eks-controller: error creating nodegroup: operation error EKS: CreateNodegroup, https response error StatusCode: 400, RequestID: 5a7a3724-739f-42e4-be3b-2507149a5611, InvalidRequestException: Volume of size 1GB is smaller than snapshot 'snap-0fae3e0968801e0df', expect size>= 20GB, requeuing"
Thu, Oct 3 2024 12:10:00 pm
time="2024-10-03T10:10:00Z" level=error msg="Error recording ekscc [ (id: )] failure message: Operation cannot be fulfilled on eksclusterconfigs.eks.cattle.io \"c-jkqpn\": the object has been modified; please apply your changes to the latest version and try again"
```

**AFTER**
When doing the same on fixed version the error `Error recording ekscc [ (id: )]` is not present anymore:
```
time="2024-10-03T14:51:50Z" level=error msg="error syncing 'cattle-global-data/c-pfnxc': handler eks-controller: error creating nodegroup: operation error EKS: CreateNodegroup, https response error StatusCode: 400, RequestID: 34a72516-8320-44be-9f70-95dbc8ece106, InvalidRequestException: Volume of size 1GB is smaller than snapshot 'snap-0fae3e0968801e0df', expect size>= 20GB, requeuing"
```

Closing as fixed.

**Closed by thehejik** 2024-10-03 14:58 UTC
Labels: kind/bug
